# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Map' do
  use_frameworks!

  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
end
